ecip:
  devMode: true
  appId: 65
  logEnum: LOG_ENUM_BOTH
  enable-tenant: false
  #id生成配置
  #当有多个web服务器时，workerId应该设置为不同
  workerId: 0
  #数据中心id
  dataCenterId: 0
  cas:
    enabled: false
    prefixUrl: http://it.hgits.cn/cas/  #验证ticket的cas地址，可以是内网
    loginUrl: ${ecip.cas.prefixUrl}login   #未登录时跳转的cas登录地址，一般是外网地址
    serviceUrl: http://localhost:8889/layui
    callbackUrl: ${ecip.cas.serviceUrl}/callback?appId=${ecip.appId}
    logoutUrl: ${ecip.cas.prefixUrl}logout
  jwt:
    #    半个小时
    expiration: 1800
  login-retry-count: 5
  login-captcha: true
  change-pwd-first-login: false
  login-encrypt: true
  login-private-key: MIICdgIBADANBgkqhkiG9w0BAQEFAASCAmAwggJcAgEAAoGAdOyfDA293nafMBuL8uW/Z+MjIoAy44U1TVhZNRmTbdbKDe0SfbfjhLsFePW56c5HhBz4sqN1IVwe7xx93mU4fkere/bxk7FTZ0llRNlHNo8wRbnhRGcJBLAbMFCJeppXI1un81IDIpJWrFQ++hhzeGy+sxxUaKYrmuuWsb1jXKECAwEAAQKBgGkLuOx8YAvAqM3wwa/sxyTPhN5XLOEJ6VRevm6dVr3EzezrA8Tc89Rorcb5hRjQUaIY4Tqk7fOVrtkF0POAHtrjDWym+xpbF0aV3Pn4h+WVghzZH8i6LWJHMqk+LVGODU5poieDV13ma5nENQVbuv7vzQWqyJr8HI2aRdP+TR9BAkEAx064kKV81EkujmUnG+dXeNqOBEdUZY4RJ2jU8e4mmCjndSUqw0hLTh8DYJp6IWOXlIxrIKAB1hALkng2sHVf6QJBAJYu4HfH/FB3GUktvmaw5OB7qh8Ei1kEHM5ZrxWwpabag137/lj8aRd0IBo303Rc1DFpQQXodKdM3ugg2V+Pm/kCQQC2mj0m6TexF0t8Uti+C/psU3ECIogEc2DsBnPzJApgJjnJbj/7ouS7slZZz65NoP1jsDMGNRL5mMHBdDpG+YLhAkBznx1TOlTnQfnmm+AFQVTD+pELlj0NyBvBRcyEn1246mvOtI2pxpHF67I3XRlfcYQvkj/sI32Du6u0/G09o9tJAkEAotfGVfMsLAwwcOv/lPIQEg508BEcYpnOMB7boqJMAwC2OsmcfLnDYhkROHWzPkg24PLDr6xHpKrQW0JKD23cAA==
  shiro-filter:
    - /api/v1/largescreen/**:anon
shiro-redis:
  redis-manager:
    deploy-mode: standalone #sentinel, cluster
    host: ${spring.redis.host}:${spring.redis.port}
    password: ${spring.redis.password}
    database: ${spring.redis.database}
    expire: ${spring.redis.expireTime}

spring:
  profiles:
    active: alone,jar,test

mybatis-plus:
  # 如果是放在src/main/java目录下 classpath:/com/yourpackage/*/mapper/*Mapper.xml
  # 如果是放在resource目录 classpath:/mapper/*Mapper.xml
  mapper-locations: classpath:/com/hgsoft/**/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
#  typeAliasesPackage: com.hgsoft.*.*.*.entity
  global-config:
    db-config:
        #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
        id-type: input
        #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
        field-strategy: NOT_NULL
        #驼峰下划线转换
#        db-column-underline: true
        #mp2.3+ 全局表前缀 mp_
        #table-prefix: mp_
        #刷新mapper 调试神器
        #refresh-mapper: true
        #数据库大写下划线转换
        #capital-mode: true
        # Sequence序列接口实现类配置
    #    key-generator: com.baomidou.mybatisplus.incrementer.OracleKeyGenerator
        #逻辑删除配置（下面3个配置）
        logic-delete-value: 1
        logic-not-delete-value: 0
    #    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
        #自定义填充策略接口实现
    #    meta-object-handler: com.baomidou.springboot.MyMetaObjectHandler
  configuration:
    #配置返回数据库(column下划线命名&&返回java实体是驼峰命名)，自动匹配无需as（没开启这个，SQL需要写as： select user_id as userId）
    map-underscore-to-camel-case: true
    cache-enabled: false
    #配置JdbcTypeForNull, oracle数据库必须配置
    jdbc-type-for-null: 'null'